[package]
name = "parse_torrent"
version = "0.1.0"
authors = ["craig OConnor <oconnorct1@gmail.com>"]

[dependencies]
chrono = "0.3"
rustc-serialize = "0.3"

[dependencies.bencode]
git = "https://github.com/arjantop/rust-bencode"
